import { Chain } from '@/types';

/**
 * Specify the chains for token list generation.
 */
export const CHAINS: Chain[] = [
    {
        id: 'ethereum',
        name: 'ethereum',
        chainId: 1,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'ropsten',
        name: 'ropsten',
        chainId: 3,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'rinkeby',
        name: 'rinkeby',
        chainId: 4,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'optimistic',
        name: 'optimistic',
        chainId: 10,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'kardiachain',
        name: 'kardiachain',
        chainId: 24,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'cronos',
        name: 'cronos',
        chainId: 25,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'bnb',
        name: 'bnb',
        chainId: 56,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'base',
        name: 'base',
        chainId: 8453,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'sokol',
        name: 'sokol',
        chainId: 77,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'chapel',
        name: 'chapel',
        chainId: 97,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'sokol',
        name: 'sokol',
        chainId: 77,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'xdai',
        name: 'xdai',
        chainId: 100,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'fuse',
        name: 'fuse',
        chainId: 122,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'heco',
        name: 'heco',
        chainId: 128,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'fantom',
        name: 'fantom',
        chainId: 250,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'boba',
        name: 'boba',
        chainId: 288,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'polygon',
        name: 'polygon',
        chainId: 137,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'mumbai',
        name: 'mumbai',
        chainId: 80001,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'xlayer',
        name: 'xlayer',
        chainId: 196,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'xlayer_testnet',
        name: 'xlayer_testnet',
        chainId: 195,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'stardust',
        name: 'stardust',
        chainId: 588,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'astar',
        name: 'astar',
        chainId: 592,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'conflux',
        name: 'conflux',
        chainId: 1030,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'metis',
        name: 'metis',
        chainId: 1088,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'manta',
        name: 'manta',
        chainId: 169,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'linea',
        name: 'linea',
        chainId: 59144,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'moonbeam',
        name: 'moonbeam',
        chainId: 1284,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'moonriver',
        name: 'moonriver',
        chainId: 1285,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'arbitrum',
        name: 'arbitrum',
        chainId: 42161,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'celo',
        name: 'celo',
        chainId: 42220,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'avalanche',
        name: 'avalanche',
        chainId: 43114,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'aurora',
        name: 'aurora',
        chainId: 1313161554,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'harmony',
        name: 'harmony',
        chainId: 1666600000,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'harmony_testnet',
        name: 'harmony_testnet',
        chainId: 1666700000,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'palm',
        name: 'palm',
        chainId: 11297108109,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'zksync',
        name: 'zksync',
        chainId: 324,
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
    {
        id: 'solana',
        name: 'solana',
        chainId: 'solana',
        assetId: '',
        coinMarketCapId: '',
        coinGeckoId: '',
    },
];
