name: Fetch token list

on:
  push:
    branches:
      - 'test-explorer'
  workflow_dispatch:

jobs:
  fetch-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node_modules cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            node_modules
          key: yarn-${{ hashFiles('package.json') }}-${{ hashFiles('yarn.lock') }}

      - name: Yarn install
        run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      # - name: Sync Token List OP
      #   id: sync-token-list-op
      #   run: |
      #     node node_modules/puppeteer/install.js && yarn cli generate -i 10 && yarn lint-fix

      # - name: Sync Token List Aurora
      #   id: sync-token-list-aurora
      #   run: |
      #     node node_modules/puppeteer/install.js && yarn cli generate -i 1313161554 && yarn lint-fix

      - name: Sync Token List Gnosis
        id: sync-token-list-gnosis
        run: |
          node node_modules/puppeteer/install.js && yarn cli generate -i 100 && yarn lint-fix

      - name: Prettier Check
        run: yarn prettier

      - name: Build
        run: yarn build

      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Tag Package Version
        run: git tag v${{ steps.package-version.outputs.current-version }}

      - name: Create Release Package
        uses: montudor/action-zip@v1
        with:
          args:
            zip -qq -r v${{ steps.package-version.outputs.current-version }}.zip dist/v${{
            steps.package-version.outputs.current-version }}

      - name: Upload Latest Release
        uses: actions/upload-artifact@v2
        with:
          name: v${{ steps.package-version.outputs.current-version }}.zip
          path: v${{ steps.package-version.outputs.current-version }}.zip

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: v${{ steps.package-version.outputs.current-version }}.zip
          asset_name: v${{ steps.package-version.outputs.current-version }}.zip
          tag: v${{ steps.package-version.outputs.current-version }}
          overwrite: true

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./dist
      #     keep_files: true
      #     cname: tokens.r2d2.to
