name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Depoly
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Install
        run: yarn install

      - name: Prettier Check
        run: yarn prettier

      - name: Build
        run: yarn build

      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Tag Package Version
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ steps.package-version.outputs.current-version }}
          message: v${{ steps.package-version.outputs.current-version }}

      - name: Create Release Package
        uses: montudor/action-zip@v1
        with:
          args:
            zip -qq -r v${{ steps.package-version.outputs.current-version }}.zip
            dist/v${{ steps.package-version.outputs.current-version }}

      - name: Upload Latest Release
        uses: actions/upload-artifact@v2
        with:
          name: v${{ steps.package-version.outputs.current-version }}.zip
          path: v${{ steps.package-version.outputs.current-version }}.zip

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: v${{ steps.package-version.outputs.current-version }}.zip
          asset_name: v${{ steps.package-version.outputs.current-version }}.zip
          tag: v${{ steps.package-version.outputs.current-version }}
          overwrite: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
          cname: tokens.r2d2.to