name: Fetch token list

on:
  #  schedule:
  #    - cron: '0 10 1 * 1,4'
  push:
    branches: ['autoDeploy']
  workflow_dispatch:

jobs:
  fetch-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node_modules cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            node_modules
          key: yarn-${{ hashFiles('package.json') }}-${{ hashFiles('yarn.lock') }}

      - name: Yarn install
        run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Sync Token List
        id: sync-token-list
        run: |
          yarn cli generate && yarn lint-fix

      - name: Create Release Package
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r test.zip src/fungible-tokens

      - name: Upload Latest Release
        uses: actions/upload-artifact@v2
        with:
          name: test.zip
          path: test.zip
