name: Fetch token list

on:
  push:
    branches:
      - 'master'
      - 'releases/**'
#  schedule:
#    - cron: '0 10 1 * 1,4'
#  workflow_dispatch:

jobs:
  fetch-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Use node_modules cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            node_modules
          key: yarn-${{ hashFiles('package.json') }}-${{ hashFiles('yarn.lock') }}

      - name: Yarn install
        run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Sync Token List
        id: sync-token-list
        run: |
          yarn generate 1

      - name: Git Diff
        id: git-diff
        if: success()
        run: |
          echo "GIT_DIFF<<EOF" >> $GITHUB_ENV
          git diff >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      #      - id: get-pr-body
      #        run: |
      #          body=$(cat pr-body.txt)
      #          delimiter="$(openssl rand -hex 8)"
      #          echo "body<<$delimiter" >> $GITHUB_OUTPUT
      #          echo "$body" >> $GITHUB_OUTPUT
      #          echo "$delimiter" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: sync ethereum token list from providers'
          committer: Maskbook maintainer bot <bot@mask.io>
          author: Maskbook maintainer bot <bot@mask.io>
          branch: auto-sync-token-list
          title: 'chore: sync token list from providers'
          #          body: '## (🤖 I am a robot) updates token list'
          #          body: ${{ steps.get-pr-body.outputs.body }}
          assignees: |
            lanttcat
          draft: false

      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
