name: Read contract

on:
  push:
    branches:
      - 'read-contract'
  workflow_dispatch:

jobs:
  read-contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node_modules cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            node_modules
          key: npm-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}

      - name: npm install
        run: npm install
        if: steps.npm-cache.outputs.cache-hit != 'true'

      - name: Sync Polygon Token List
        id: sync-token-list-polygon
        run: |
          node node_modules/puppeteer/install.js && npm run read-contract && npm run lint-fix
